;; SPDX-License-Identifier: GPL-3.0-or-later OR Apache-2.0
;; CLONE_GATE: mu_kanren_lattice_kernel
;;
;; mu_kanren.scm — production μKanren + miniKanren kernel (R5RS / R7RS)
;; Relational core: == fresh conde run  |  constraints: =/= symbolo numbero absento
;; Streams are immature thunks; mplus interleaves. No mutation except var counter.
;; Kernel for LATTICE-style relational refinement.

(define *var-idx* 0)
(define (var name)
  (set! *var-idx* (+ *var-idx* 1))
  (vector name *var-idx*))
(define (var? x) (vector? x))
(define (var=? u v) (= (vector-ref u 1) (vector-ref v 1)))

(define (walk u s)
  (let ((pr (and (var? u) (assp (lambda (v) (var=? u v)) s))))
    (if pr (walk (cdr pr) s) u)))

(define (assp p alist)
  (cond ((null? alist) #f)
        ((p (caar alist)) (car alist))
        (else (assp p (cdr alist)))))

(define (ext-s x v s) (cons (cons x v) s))

(define (occurs? x v s)
  (let ((v (walk v s)))
    (cond ((var? v) (var=? x v))
          ((pair? v) (or (occurs? x (car v) s) (occurs? x (cdr v) s)))
          (else #f))))

(define (unify u v s)
  (let ((u (walk u s)) (v (walk v s)))
    (cond
      ((eq? u v) s)
      ((var? u) (if (occurs? u v s) #f (ext-s u v s)))
      ((var? v) (if (occurs? v u s) #f (ext-s v u s)))
      ((and (pair? u) (pair? v))
       (let ((s (unify (car u) (car v) s)))
         (and s (unify (cdr u) (cdr v) s))))
      ((equal? u v) s)
      (else #f))))

(define (unit s/c) (cons s/c mzero))
(define mzero '())
(define (mplus $1 $2)
  (cond ((null? $1) $2)
        ((procedure? $1) (lambda () (mplus $2 ($1))))
        (else (cons (car $1) (mplus (cdr $1) $2)))))
(define (bind $ g)
  (cond ((null? $) mzero)
        ((procedure? $) (lambda () (bind ($) g)))
        (else (mplus (g (car $)) (bind (cdr $) g)))))

(define (== u v)
  (lambda (s/c)
    (let ((s (unify u v (car s/c))))
      (if s (unit (cons s (cdr s/c))) mzero))))

(define succeed (lambda (s/c) (unit s/c)))
(define fail (lambda (s/c) mzero))

(define (conj2 g1 g2) (lambda (s/c) (bind (g1 s/c) g2)))
(define (disj2 g1 g2) (lambda (s/c) (mplus (g1 s/c) (g2 s/c))))

(define-syntax conj
  (syntax-rules ()
    ((_) succeed)
    ((_ g) g)
    ((_ g0 g ...) (conj2 g0 (conj g ...)))))
(define-syntax disj
  (syntax-rules ()
    ((_) fail)
    ((_ g) g)
    ((_ g0 g ...) (disj2 g0 (disj g ...)))))
(define-syntax conde
  (syntax-rules ()
    ((_ (g ...) ...) (disj (conj g ...) ...))))
(define-syntax fresh
  (syntax-rules ()
    ((_ (x ...) g ...)
     (lambda (s/c)
       (let ((x (var 'x)) ...)
         ((conj g ...) s/c))))))

(define (call/fresh f)
  (lambda (s/c)
    (let ((c (cdr s/c)))
      ((f (var c)) (cons (car s/c) (+ c 1))))))

(define (pull $) (if (procedure? $) (pull ($)) $))
(define (take n $)
  (if (and n (zero? n)) '()
      (let (($ (pull $)))
        (cond ((null? $) '())
              (else (cons (car $) (take (and n (- n 1)) (cdr $))))))))

(define (reify-s v s)
  (let ((v (walk v s)))
    (cond ((var? v)
           (ext-s v (reify-name (length s)) s))
          ((pair? v) (reify-s (cdr v) (reify-s (car v) s)))
          (else s))))
(define (reify-name n)
  (string->symbol (string-append "_" (number->string n))))
(define (walk* v s)
  (let ((v (walk v s)))
    (cond ((var? v) v)
          ((pair? v) (cons (walk* (car v) s) (walk* (cdr v) s)))
          (else v))))
(define (reify v)
  (lambda (s/c)
    (let ((v (walk* v (car s/c))))
      (walk* v (reify-s v '())))))

(define-syntax run
  (syntax-rules ()
    ((_ n (x) g ...)
     (map (reify x)
          (take n ((fresh (x) g ...) '(() . 0)))))))
(define-syntax run*
  (syntax-rules ()
    ((_ (x) g ...) (run #f (x) g ...))))

;; ---------- constraints (cKanren-lite) ----------
(define (=/= u v)
  (lambda (s/c)
    (let ((s (unify u v (car s/c))))
      (if (not s) (unit s/c)
          (if (eq? s (car s/c)) mzero (unit s/c))))))

(define (symbolo x)
  (lambda (s/c)
    (let ((x (walk x (car s/c))))
      (if (or (var? x) (symbol? x)) (unit s/c) mzero))))
(define (numbero x)
  (lambda (s/c)
    (let ((x (walk x (car s/c))))
      (if (or (var? x) (number? x)) (unit s/c) mzero))))
(define (absento tag t)
  (lambda (s/c)
    (letrec ((rec (lambda (v)
                    (cond ((equal? v tag) #f)
                          ((pair? v) (and (rec (car v)) (rec (cdr v))))
                          (else #t)))))
      (if (rec (walk* t (car s/c))) (unit s/c) mzero))))

;; ---------- lists ----------
(define (conso a d p) (== `(,a . ,d) p))
(define (nullo x) (== '() x))
(define (pairo p) (fresh (a d) (conso a d p)))
(define (caro p a) (fresh (d) (conso a d p)))
(define (cdro p d) (fresh (a) (conso a d p)))
(define (listo l)
  (conde ((nullo l))
         ((fresh (a d) (conso a d l) (listo d)))))
(define (appendo l s o)
  (conde ((nullo l) (== s o))
         ((fresh (a d res)
            (conso a d l) (conso a res o) (appendo d s res)))))
(define (membero x l)
  (fresh (a d)
    (conso a d l)
    (conde ((== a x)) ((membero x d)))))
(define (rembero x l o)
  (conde ((nullo l) (nullo o))
         ((fresh (a d)
            (conso a d l)
            (conde ((== a x) (== d o))
                   ((=/= a x) (fresh (res) (conso a res o) (rembero x d res))))))))
(define (reverseo l o)
  (letrec ((rev (lambda (ll acc oo)
                  (conde ((nullo ll) (== acc oo))
                         ((fresh (a d) (conso a d ll) (rev d `(,a . ,acc) oo)))))))
    (rev l '() o)))
(define (lengtho l n)
  (conde ((nullo l) (== n 'z))
         ((fresh (a d n1) (conso a d l) (== n `(s . ,n1)) (lengtho d n1)))))
(define (flatteno l o)
  (conde ((nullo l) (nullo o))
         ((fresh (a d fa fd)
            (conso a d l) (pairo a) (flatteno a fa) (flatteno d fd) (appendo fa fd o)))
         ((fresh (a d res)
            (conso a d l) (flatteno d res) (conso a res o)))))
(define (distincto l)
  (conde ((nullo l))
         ((fresh (a d) (conso a d l) (absento a d) (distincto d)))))
(define (permuteo l o)
  (conde ((nullo l) (nullo o))
         ((fresh (a d res) (conso a d l) (rembero a o res) (permuteo d res)))))

;; ---------- Peano ----------
(define (zeroo n) (== n 'z))
(define (succo n n1) (== n1 `(s . ,n)))
(define (nato n)
  (conde ((zeroo n)) ((fresh (p) (succo p n) (nato p)))))
(define (addo x y z)
  (conde ((zeroo x) (== y z))
         ((fresh (x1 z1) (succo x1 x) (succo z1 z) (addo x1 y z1)))))
(define (mulo x y z)
  (conde ((zeroo x) (zeroo z))
         ((fresh (x1 z1) (succo x1 x) (mulo x1 y z1) (addo y z1 z)))))

;; ---------- full adder (bit relations) ----------
(define (bit-xoro x y r)
  (conde ((== x 0) (== y 0) (== r 0))
         ((== x 0) (== y 1) (== r 1))
         ((== x 1) (== y 0) (== r 1))
         ((== x 1) (== y 1) (== r 0))))
(define (bit-ando x y r)
  (conde ((== x 0) (== y 0) (== r 0))
         ((== x 0) (== y 1) (== r 0))
         ((== x 1) (== y 0) (== r 0))
         ((== x 1) (== y 1) (== r 1))))
(define (half-addero x y r c)
  (conj (bit-xoro x y r) (bit-ando x y c)))
(define (full-addero b x y r c)
  (fresh (w xy wz)
    (half-addero x y w xy)
    (half-addero w b r wz)
    (bit-xoro xy wz c)))

;; ---------- evalo (relational Scheme subset) ----------
(define (lookupo x env v)
  (fresh (y vy rest)
    (== `((,y . ,vy) . ,rest) env)
    (conde ((== x y) (== v vy))
           ((=/= x y) (lookupo x rest v)))))
(define (eval-expro expr env val)
  (conde
    ((fresh (q) (== `(quote ,q) expr) (== q val)))
    ((symbolo expr) (lookupo expr env val))
    ((fresh (p b) (== `(lambda (,p) ,b) expr) (== `(closure ,p ,b ,env) val)))
    ((fresh (rator rand clo arg)
       (== `(,rator ,rand) expr)
       (eval-expro rator env clo)
       (eval-expro rand env arg)
       (apply-expro clo arg val)))
    ((fresh (a d va vd)
       (== `(cons ,a ,d) expr)
       (eval-expro a env va) (eval-expro d env vd)
       (== `(,va . ,vd) val)))
    ((fresh (c t e cv)
       (== `(if ,c ,t ,e) expr)
       (eval-expro c env cv)
       (conde ((== cv #t) (eval-expro t env val))
              ((== cv #f) (eval-expro e env val)))))))
(define (apply-expro clo arg val)
  (fresh (p b env)
    (== `(closure ,p ,b ,env) clo)
    (eval-expro b `((,p . ,arg) . ,env) val)))
(define (evalo expr val) (eval-expro expr '() val))

;; ---------- Formulog-shaped path with SMT stub ----------
(define *edges* '())
(define (assert-edge a b phi)
  (set! *edges* (cons (list a b phi) *edges*)))
(define (edgeo a b phi)
  (lambda (s/c)
    (let loop ((es *edges*))
      (if (null? es) mzero
          (mplus ((fresh () (== a (caar es)) (== b (cadar es)) (== phi (caddar es))) s/c)
                 (loop (cdr es)))))))
(define (smt-sat? phi)
  (define (neg p) (and (pair? p) (eq? (car p) 'not) (cadr p)))
  (define (atoms p)
    (cond ((and (pair? p) (eq? (car p) 'and))
           (append (atoms (cadr p)) (atoms (caddr p))))
          (else (list p))))
  (let ((as (atoms phi)))
    (let loop ((xs as) (pos '()) (negd '()))
      (cond ((null? xs) #t)
            ((neg (car xs))
             (if (member (neg (car xs)) pos) #f
                 (loop (cdr xs) pos (cons (neg (car xs)) negd))))
            (else
             (if (member (car xs) negd) #f
                 (loop (cdr xs) (cons (car xs) pos) negd)))))))
(define (is-sato phi flag)
  (lambda (s/c)
    (let ((p (walk* phi (car s/c))))
      ((== flag (smt-sat? p)) s/c))))
(define (patho x y p phi)
  (conde
    ((fresh (e)
       (edgeo x y e) (== p `(,y)) (== phi e) (is-sato e #t)))
    ((fresh (z e p2 phi2)
       (edgeo x z e)
       (patho z y p2 phi2)
       (== p `(,z . ,p2))
       (== phi `(and ,e ,phi2))
       (is-sato phi #t)))))

(assert-edge 0 1 '(bv-slt x y))
(assert-edge 1 2 '(bv-slt y z))
(assert-edge 2 3 '(and p (not q)))

;; ---------- FSM / refine (LATTICE-adjacent) ----------
(define (fsmo st inp nst out)
  (conde
    ((== st 's0) (== inp 0) (== nst 's0) (== out 0))
    ((== st 's0) (== inp 1) (== nst 's1) (== out 0))
    ((== st 's1) (== inp 0) (== nst 's0) (== out 1))
    ((== st 's1) (== inp 1) (== nst 's1) (== out 1))))
(define (refineo absv conc)
  (conde ((== absv conc))
         ((== absv 'top))
         ((fresh (lo hi) (== absv `(interval ,lo ,hi))))))

;; smoke tests:
;; (run 3 (q) (appendo '(1 2) '(3) q))    => ((1 2 3))
;; (run 1 (q) (evalo '(quote (a b)) q))   => ((a b))
;; (run* (q) (addo '(s . z) '(s . z) q)) => ((s s . z))
;; (run* (q) (full-addero 0 1 1 q 1))     => (0)
